name: Build and test

on:
  pull_request:
    branches: ["main"]

env:
  CONFIGURATION: Debug
  NODE_VERSION: "16.x"
  DOTNET_VERSION: 6.0.x
  PROJECT_DIRECTORY: Src
  FRONTEND_DIRECTORY: Src/LoansComparer.WebClient
  BACKEND_DIRECTORY: Src/LoansComparer.WebAPI

concurrency:
  group: build

jobs:
  dotnet-format:
    runs-on: windows-latest

    steps:
      - name: Get branch info
        id: branch-info
        uses: xt0rted/pull-request-comment-branch@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.branch-info.outputs.ref }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Custom dotnet code formatting
        run: |
          dotnet format whitespace
          dotnet format style --severity info
        working-directory: ${{ env.PROJECT_DIRECTORY }}

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Automated dotnet-format update 
          Co-authored-by: ${{ github.actor }}'
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: windows-latest
    needs: dotnet-format

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "${{ env.FRONTEND_DIRECTORY }}/package-lock.json"

      - name: Npm install
        run: npm install
        working-directory: ${{ env.FRONTEND_DIRECTORY }}

      - name: Restore dependencies
        run: dotnet restore "${{ env.PROJECT_DIRECTORY }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test "${{ env.PROJECT_DIRECTORY }}" --no-build
